In [1]:
import numpy as np
P = np.array([[1,7],[2,1],[3,2]])
print(P)

[[1 7]
 [2 1]
 [3 2]]


In [4]:
Q = np.array([[1,1], [1,-1], [1,0]])
print(Q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [6]:
C1 = np.add(P,Q)
print(C1)

[[2 8]
 [3 0]
 [4 2]]


In [7]:
C2 = np.subtract(P,Q)
print(C2)

[[0 6]
 [1 2]
 [2 2]]


In [8]:
R = np.array([[1,3,1],[1,0,1]])
print(R)

[[1 3 1]
 [1 0 1]]


In [10]:
C3 = np.dot(P,R)
print(C3)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [13]:
det = np.linalg.det(C3)
print(det)

0.0


In [14]:
S2 = np.linalg.inv(det)

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

In [15]:
M = np.array([[1,-1],[2,3]])
print(np.linalg.inv(M))

[[ 0.6  0.2]
 [-0.4  0.2]]
