In [3]:
import sys
!{sys.executable} -m pip install --user numpy

In [4]:
import numpy as np

In [5]:
v=np.array([1,-1,2])
w=np.array([2,5,2])

In [6]:
print(v+w)

[3 4 4]


In [7]:
print(v-w)

[-1 -6  0]


In [8]:
#scaller Multiplication
print(3*v)

[ 3 -3  6]


In [9]:
print(np.linalg.norm(v))

2.449489742783178


In [10]:
s = np.dot(v,w)
print(s)

1
