Linear Algebra 

In [4]:
import numpy as np

In [5]:
x = np.array([[1],[2],[3]])

In [6]:
x.shape

(3, 1)

In [7]:
y = np.array([[1],[2],[3]])

In [8]:
z = x+y
print(z)

[[2]
 [4]
 [6]]


In [9]:
print(np.add(x,y))

[[2]
 [4]
 [6]]


In [10]:
alpha = 2
print(alpha*z)

[[ 4]
 [ 8]
 [12]]


In [11]:
a = 2
b = 3
x = np.array([[2],[3]])
y = np.array([[4],[5]])
z = (a*x)+(b*y)
print(z)

[[16]
 [21]]


In [12]:
a, b = 2, 3
x, y = np.array([[2], [3]]), np.array([[4], [5]])

a*x + b* y

array([[16],
       [21]])

In [13]:
x, y = np.array([[-2], [2]]), np.array([[4], [-3]])
x.T @ y

array([[-14]])

In [15]:
x.T

array([[-2,  2]])

In [20]:
#Euclidean norm
x = np.array([[3],[4],[2]])
np.linalg.norm(x,2)

5.385164807134505

In [21]:
#MAnhattan norm
x = np.array([[3],[4],[2]])
np.linalg.norm(x,1)

9.0

In [24]:
#Max norm
x = np.array([[3],[4],[-8]])
np.linalg.norm(x,np.inf)

8.0

In [25]:
#Distance between 2 pair of vector
x, y = np.array([[3],[4],[-8]]), np.array([[2],[5],[-2]])
distance = np.linalg.norm(x-y,2)
print(distance)

6.164414002968975


In [27]:
# Vector angles and orthogonality
x, y = np.array([[3],[4]]), np.array([[2],[5]])
cos_theta = (x.T @ y)  / (np.linalg.norm(x,2) * np.linalg.norm(y,2))
print(f'cos of the angle = {np.round(cos_theta, 3)}')

#This is a necessary conclusion (range between −1,1) since the numerator in the equation always is going to be smaller or equal to the denominator.

cos of the angle = [[0.966]]


In [ ]:
# We get that cosθ≈0.966
# . Finally, to know the exact value of θ
#  we need to take the trigonometric inverse of the cosine function as:

In [28]:
cos_inverse = np.arccos(cos_theta)
print(f'angle in radiants = {np.round(cos_inverse, 3)}')

angle in radiants = [[0.263]]


In [29]:
#f'angle in degrees
degrees = cos_inverse * ((180)/np.pi)
print(f'angle in degrees = {np.round(degrees, 3)}')

angle in degrees = [[15.068]]


In [36]:
import pandas as pd
import altair as alt
df = pd.DataFrame({"x1": [0, 2], "y1":[8, 3], "x2": [0.5, 2], "y2": [0, 3]})
equation1 = alt.Chart(df).mark_line().encode(x="x1", y="y1")
equation2 = alt.Chart(df).mark_line(color="red").encode(x="x2", y="y2")
equation1 + equation2

alt.LayerChart(...)

In [37]:
A = np.array([[0,2],[1,4]])
print(A)

[[0 2]
 [1 4]]


In [38]:
A = np.array([[0,2],
              [1,4]])
B = np.array([[3,1],
              [-3,2]])

In [39]:
A+B

array([[ 3,  3],
       [-2,  6]])

In [40]:
np.add(A,B)

array([[ 3,  3],
       [-2,  6]])

In [41]:
alpha

2

In [42]:
alpha*A

array([[0, 4],
       [2, 8]])

In [44]:
np.multiply(A,alpha)

array([[0, 4],
       [2, 8]])

In [45]:
A = np.array([[0,2],
              [1,4]])
x = np.array([[1],
              [2]])

In [47]:
A @ x

array([[4],
       [9]])

In [49]:
np.dot(A,x)

array([[4],
       [9]])

In [63]:
A = np.array([[0,2],
              [1,4]])
B = np.array([[1,3],
              [2,1]])

In [68]:
#Dot Product
print(A@B)
print("--------------")
#hadamard Product
print(np.multiply(A,B))
print("--------------")
print(A*B)

[[4 2]
 [9 7]]
--------------
[[0 6]
 [2 4]]
--------------
[[0 6]
 [2 4]]


In [52]:
np.dot(A,B)

array([[4, 2],
       [9, 7]])

In [53]:
#Matrix Inverse
A = np.array([[1, 2, 1],
              [4, 4, 5],
              [6, 7, 7]])

In [57]:
A_i = np.linalg.inv(A)
print(f'A inverse:\n{A_i}')

I = np.round(A_i @ A)
print(I)

A_i_i = np.linalg.inv(A_i)
print(f'A_i inverse:\n{A_i_i}')

A inverse:
[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]
A_i inverse:
[[1. 2. 1.]
 [4. 4. 5.]
 [6. 7. 7.]]


In [58]:
#Matrix Transpose
A.T

array([[1, 4, 6],
       [2, 4, 7],
       [1, 5, 7]])

In [69]:
import scipy

In [73]:
v = np.array([1,2,3]).reshape(3,1)
print(v)

v = np.array([1,2,3]).reshape(-1,1)
print(v)

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [75]:
np.zeros((3,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [76]:
np.ones((3,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [78]:
np.random.rand(3,2)

array([[0.29265705, 0.1202457 ],
       [0.88985257, 0.68401828],
       [0.69146246, 0.91341301]])

In [80]:
np.random.randn(3,2)

array([[-0.90040134,  0.47092798],
       [ 0.50113926, -0.32949066],
       [ 1.32867956, -0.41515585]])