In [1]:
In [1]: import scipy

In [2]:
import numpy as np

In [3]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
A.dtype

dtype('int32')

In [5]:
A.shape

(3, 2)

In [8]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [9]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.random.rand(2,2)

array([[0.52223378, 0.98516763],
       [0.63010238, 0.96563291]])

In [14]:
np.ones((3,2))*10

array([[10., 10.],
       [10., 10.],
       [10., 10.]])

In [17]:
A = 10 * np.ones((2,2))
B = np.array([[2,4],[3,2]])
A*B

array([[20., 40.],
       [30., 20.]])

In [18]:
A@B

array([[50., 60.],
       [50., 60.]])

In [19]:
import numpy as np
from scipy import linalg


In [20]:
A = np.array([[3,2],[2,-1]])
B = np.array([12,1]).reshape((2,1))

In [21]:
A

array([[ 3,  2],
       [ 2, -1]])

In [22]:
B

array([[12],
       [ 1]])

In [23]:
x = linalg.solve(A,B)
x

array([[2.],
       [3.]])

In [26]:
A = np.array([
   [1, 9, 2, 1, 1],
   [10, 1, 2, 1, 1],
   [1, 0, 5, 1, 1],
   [2, 1, 1, 2, 9],
   [2, 1, 2, 13, 2],
   ])

In [31]:
B = np.array([150,200,140,180,350]).reshape((5,1))

In [32]:
x = linalg.solve(A,B)
x

array([[12.34668086],
       [ 7.64001596],
       [19.58671456],
       [19.91397277],
       [ 9.80577358]])